import Head from 'next/head';
import React  from 'react';
import Typography from '@mui/material/Typography';
import Navbar from './share/Navbar';
import { Box } from '@mui/material';

const Layout = ({children}) => {
    
    return (
        <>
           <header>
           <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
            
            </header> 
            <main>
                {children}
            </main>
            <footer>
                <Box sx={{border:"1px solid gray"}}>
                    
            <Typography variant="small" sx={{textAlign:"center"}} component="h6">
             Evaly is bangladeh most popular e-commerce website copywritte 2022
            </Typography>
                </Box>
            </footer>
        </>
    );
};

export default Layout;